In [1]:
import pandas as pd
import numpy as np

In [5]:
import seaborn as sns

In [6]:
df=pd.read_csv('emails.csv')

In [7]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [8]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [11]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [12]:
x=df.text.values



In [13]:
y=df.spam.values

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.2)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv=CountVectorizer()
x_train=cv.fit_transform(xtrain)

In [18]:
x_train.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
model=MultinomialNB()

In [21]:
model.fit(x_train,ytrain)

MultinomialNB()

In [22]:
x_test=cv.transform(xtest)

In [23]:
x_test.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
model.score(x_test,ytest)

0.9894644424934153

In [25]:
emails=['hey i am looking for machine learning tutorial in bengali language.','hey, you won a iphone 14 for free. so do the survey.']

In [26]:
cv_emails=cv.transform(emails)

In [27]:
model.predict(cv_emails)

array([0, 1], dtype=int64)

# performance

In [29]:
pred=model.predict(x_test)

In [30]:
pred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
accuracy_score(ytest,pred)

0.9894644424934153

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(ytest,pred)

array([[881,  10],
       [  2, 246]], dtype=int64)

In [36]:
from sklearn.metrics import classification_report

In [38]:
print(classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       891
           1       0.96      0.99      0.98       248

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.98      1139
weighted avg       0.99      0.99      0.99      1139

